version: '3'

services:
  postgresql:
    image: "bitnami/postgresql:12.3.0"
    networks:
      - micronaut-demo
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
      - "./postgresql/initdb.d:/docker-entrypoint-initdb.d:Z"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=changeme
      - PGPASSWORD=kineKine41!
      - POSTGRESQL_PASSWORD=kineKine41!
      - POSTGRESQL_MULTIPLE_DATABASES=

  backend:
    build: ../be
    image: mfeval-be
    command: sh -c '/usr/bin/wait_for postgresql:5432 -- java -jar be-0.1-all.jar'
    ports:
      - 7000:7000
    networks:
      - micronaut-demo
    depends_on:
      - postgresql
    environment:
      - JDBC_URL=jdbc:postgresql://postgresql:5432/postgres

  frontend:
    build: ../fe
    image: mfeval-fe
    ports:
      - 7080:8080
    networks:
      - micronaut-demo
volumes:
  postgresql_data:

networks:
  micronaut-demo:
