micronaut:
  application:
    name: micronaut-demo
  server:
    port: 7000
    server:
      cors:
        enabled: true
        configurations:
          web:
            allowedOrigins:
              - http://localhost:7080

#Access SQL database with JPA and Hibernate
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:kineKine41!}
jpa.default.properties.hibernate.hbm2ddl.auto: update

flyway:
  datasources:
    default:
      locations: classpath:databasemigrations