micronaut:
  application:
    name: micronaut-demo
  server:
    port: 7000
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:7080
          allowedMethods:
            - "GET"
            - "POST"
            - "DELETE"
            - "PUT"
            - "HEAD"
            - "OPTIONS"

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:kineKine41!}


flyway:
  datasources:
    default:
    enabled: true
    schemas: public
    locations: classpath:/db/migration
    baselineOnMigrate: true
